package antoniojesus.ddns.net.contact.modelos;
// Generated 03-oct-2019 3:57:40 by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idpersona;
     private String nombre;
     private Byte esDni;
     private byte esProveedor;
     private byte esEmpresa;
     private byte esCliente;
     private byte esTrabajador;
     private Byte esHombre;
     private String documento;
     private String primerApellido;
     private String segundoApellido;
     private String departamento;
     private String categoria;
     private String comentario;
     private String email;
     private String paginaWeb;
     private String pais;
     private String ciudad;
     private String provincia;
     private String poblacion;
     private String calle;
     private String via;
     private String numero;
     private String escalera;
     private String bloque;
     private String codigoPostal;
     private String razonSocial;
     private String tipo;
     private String usuario;
     private String password;
     private String empresa;

    public Persona() {
    }

	
    public Persona(String nombre, byte esProveedor, byte esEmpresa, byte esCliente, byte esTrabajador) {
        this.nombre = nombre;
        this.esProveedor = esProveedor;
        this.esEmpresa = esEmpresa;
        this.esCliente = esCliente;
        this.esTrabajador = esTrabajador;
    }
    public Persona(String nombre, Byte esDni, byte esProveedor, byte esEmpresa, byte esCliente, byte esTrabajador, Byte esHombre, String documento, String primerApellido, String segundoApellido, String departamento, String categoria, String comentario, String email, String paginaWeb, String pais, String ciudad, String provincia, String poblacion, String calle, String via, String numero, String escalera, String bloque, String codigoPostal, String razonSocial, String tipo, String usuario, String password, String empresa) {
       this.nombre = nombre;
       this.esDni = esDni;
       this.esProveedor = esProveedor;
       this.esEmpresa = esEmpresa;
       this.esCliente = esCliente;
       this.esTrabajador = esTrabajador;
       this.esHombre = esHombre;
       this.documento = documento;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.departamento = departamento;
       this.categoria = categoria;
       this.comentario = comentario;
       this.email = email;
       this.paginaWeb = paginaWeb;
       this.pais = pais;
       this.ciudad = ciudad;
       this.provincia = provincia;
       this.poblacion = poblacion;
       this.calle = calle;
       this.via = via;
       this.numero = numero;
       this.escalera = escalera;
       this.bloque = bloque;
       this.codigoPostal = codigoPostal;
       this.razonSocial = razonSocial;
       this.tipo = tipo;
       this.usuario = usuario;
       this.password = password;
       this.empresa = empresa;
    }
   
    public Integer getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(Integer idpersona) {
        this.idpersona = idpersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Byte getEsDni() {
        return this.esDni;
    }
    
    public void setEsDni(Byte esDni) {
        this.esDni = esDni;
    }
    public byte getEsProveedor() {
        return this.esProveedor;
    }
    
    public void setEsProveedor(byte esProveedor) {
        this.esProveedor = esProveedor;
    }
    public byte getEsEmpresa() {
        return this.esEmpresa;
    }
    
    public void setEsEmpresa(byte esEmpresa) {
        this.esEmpresa = esEmpresa;
    }
    public byte getEsCliente() {
        return this.esCliente;
    }
    
    public void setEsCliente(byte esCliente) {
        this.esCliente = esCliente;
    }
    public byte getEsTrabajador() {
        return this.esTrabajador;
    }
    
    public void setEsTrabajador(byte esTrabajador) {
        this.esTrabajador = esTrabajador;
    }
    public Byte getEsHombre() {
        return this.esHombre;
    }
    
    public void setEsHombre(Byte esHombre) {
        this.esHombre = esHombre;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPaginaWeb() {
        return this.paginaWeb;
    }
    
    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getVia() {
        return this.via;
    }
    
    public void setVia(String via) {
        this.via = via;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getEscalera() {
        return this.escalera;
    }
    
    public void setEscalera(String escalera) {
        this.escalera = escalera;
    }
    public String getBloque() {
        return this.bloque;
    }
    
    public void setBloque(String bloque) {
        this.bloque = bloque;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }




}


