package com.iridiscente.contactosGaroe.modelos;
// Generated 11-oct-2019 6:53:57 by Hibernate Tools 4.3.1



/**
 * Admitido generated by hbm2java
 */
public class Admitido  implements java.io.Serializable {


     private String mac;

    public Admitido() {
    }

    public Admitido(String mac) {
       this.mac = mac;
    }
   
    public String getMac() {
        return this.mac;
    }
    
    public void setMac(String mac) {
        this.mac = mac;
    }




}


